# Importing python packages

In [1]:
import pandas as pd

# Importing the data sets
## Births registration

First we need to import the dataset. As the dataset is in CSV format the easiest way is to use 'read_csv' pandas function for this file format. 

Birth registration data (2022) Birth registration data - UNICEF DATA data.unicef.org. UNICEF. Available at: https://data.unicef.org/resources/dataset/percentage-children-age-5-whose-births-registered-sex-place-residence-household-wealth-quintile/ (Accessed: December 30, 2022).

NOTE: File name for originally generated CSV file had to be renamed as Git was throwing the ‘Filename too long’ error when tried to add it to repository.

In [2]:
CB_percent = pd.read_csv('Percent of children_UNICEF_1.0_all.csv',low_memory=False)

### Exploring the data set

In [3]:
CB_percent.shape

(1648747, 22)

In [4]:
CB_percent.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1648747 entries, 0 to 1648746
Data columns (total 22 columns):
 #   Column                                                                          Non-Null Count    Dtype  
---  ------                                                                          --------------    -----  
 0   DATAFLOW                                                                        1648747 non-null  object 
 1   REF_AREA:Geographic area                                                        1648747 non-null  object 
 2   INDICATOR:Indicator                                                             1648747 non-null  object 
 3   SEX:Sex                                                                         1648747 non-null  object 
 4   TIME_PERIOD:Time period                                                         1648747 non-null  object 
 5   OBS_VALUE:Observation Value                                                     1648747 non-null  object 

We can see that there are a lot of null data values, however no columns are totally empty, hence need to analyse to detemine what columns are of interest and which can be discarded.

#### Analysis what columns can be discarded from the original data set

In [5]:
CB_percent.groupby('DATAFLOW').nunique()

REF_AREA:Geographic area  \
DATAFLOW                                                                       
UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indic...                       330   

                                                    INDICATOR:Indicator  \
DATAFLOW                                                                  
UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indic...                  380   

                                                    SEX:Sex  \
DATAFLOW                                                      
UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indic...        3   

                                                    TIME_PERIOD:Time period  \
DATAFLOW                                                                      
UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indic...                      163   

                                                    OBS_VALUE:Observation Value  \
DATAFLOW                                                                          
UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indic...                       844052   

                                                    UNIT_MULTIPLIER:Unit multiplier  \
DATAFLOW                                                                              
UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indic...                                2   

                                                    UNIT_MEASURE:Unit of measure  \
DATAFLOW                                                                           
UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indic...                            25   

                                                    OBS_STATUS:Observation Status  \
DATAFLOW                                                                            
UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indic...                              8   

                                                    OBS_CONF:Observation confidentaility  \
DATAFLOW                                                                                   
UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indic...                                     2   

                                                    LOWER_BOUND:Lower Bound  \
DATAFLOW                                                                      
UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indic...                   289582   

                                                    ...  \
DATAFLOW                                            ...   
UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indic...  ...   

                                                    WGTD_SAMPL_SIZE:Weighted Sample Size  \
DATAFLOW                                                                                   
UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indic...                                 16445   

                                                    OBS_FOOTNOTE:Observation footnote  \
DATAFLOW                                                                                
UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indic...                               1037   

                                                    SERIES_FOOTNOTE:Series footnote  \
DATAFLOW                                                                              
UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indic...                               21   

                                                    DATA_SOURCE:Data Source  \
DATAFLOW                                                                      
UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indic...                     5007   

                                                    SOURCE_LINK:Citation of or link to the data source  \
DATAFLOW                                                                                                 
UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indic...                                                 51    

                                                    CUSTODIAN:Custodian  \
DATA

In [6]:
CB_percent.groupby('REF_AREA:Geographic area').nunique()

DATAFLOW  INDICATOR:Indicator  SEX:Sex  \
REF_AREA:Geographic area                                           
ABW: Aruba                       1                   42        3   
AFG: Afghanistan                 1                  293        3   
AGO: Angola                      1                  304        3   
AIA: Anguilla                    1                   57        3   
ALB: Albania                     1                  301        3   
...                            ...                  ...      ...   
XKX: Kosovo                      1                   47        3   
YEM: Yemen                       1                  314        3   
ZAF: South Africa                1                  314        3   
ZMB: Zambia                      1                  330        3   
ZWE: Zimbabwe                    1                  346        3   

                          TIME_PERIOD:Time period  \
REF_AREA:Geographic area                            
ABW: Aruba                                     73   
AFG: Afghanistan                               73   
AGO: Angola                                    73   
AIA: Anguilla                                  73   
ALB: Albania                                   73   
...                                           ...   
XKX: Kosovo                                    73   
YEM: Yemen                                     73   
ZAF: South Africa                              73   
ZMB: Zambia                                    73   
ZWE: Zimbabwe                                  73   

                          OBS_VALUE:Observation Value  \
REF_AREA:Geographic area                                
ABW: Aruba                                       2636   
AFG: Afghanistan                                 5419   
AGO: Angola                                      5223   
AIA: Anguilla                                    2441   
ALB: Albania                                     4907   
...                                               ...   
XKX: Kosovo                                      2471   
YEM: Yemen                                       5577   
ZAF: South Africa                                5602   
ZMB: Zambia                                      6196   
ZWE: Zimbabwe                                    6389   

                          UNIT_MULTIPLIER:Unit multiplier  \
REF_AREA:Geographic area                                    
ABW: Aruba                                              2   
AFG: Afghanistan                                        2   
AGO: Angola                                             2   
AIA: Anguilla                                           2   
ALB: Albania                                            2   
...                                                   ...   
XKX: Kosovo                                             2   
YEM: Yemen                                              2   
ZAF: South Africa                                       2   
ZMB: Zambia                                             2   
ZWE: Zimbabwe                                           2   

                          UNIT_MEASURE:Unit of measure  \
REF_AREA:Geographic area                                 
ABW: Aruba                                           8   
AFG: Afghanistan                                    25   
AGO: Angola                                         25   
AIA: Anguilla                                        7   
ALB: Albania                                        23   
...                                                ...   
XKX: Kosovo                                          6   
YEM: Yemen                                          25   
ZAF: South Africa                                   25   
ZMB: Zambia                                         25   
ZWE: Zimbabwe                                       25   

                          OBS_STATUS:Observation Status  \
REF_AREA:Geographic area                                  
ABW: Aruba                                

In [7]:
CB_percent.groupby('INDICATOR:Indicator').nunique()

DATAFLOW  \
INDICATOR:Indicator                                            
CME_ARR_10T19: Annual Rate of Reduction in Mort...         1   
CME_ARR_SBR: Annual rate of reduction in stillb...         1   
CME_ARR_U5MR: Annual rate of reduction in under...         1   
CME_MRM0: Neonatal mortality rate                          1   
CME_MRY0: Infant mortality rate                            1   
...                                                      ...   
WS_SCH_W-B: Proportion of schools with basic dr...         1   
WS_SCH_W-L: Proportion of schools with limited ...         1   
WS_SCH_W-N: Proportion of schools with no drink...         1   
WT_ADLS_15-19_ED_NEET: Percentage of adolescent...         1   
WT_ADLS_15-19_LAB_FRC_UNEMP: Percentage of adol...         1   

                                                    REF_AREA:Geographic area  \
INDICATOR:Indicator                                                            
CME_ARR_10T19: Annual Rate of Reduction in Mort...                       231   
CME_ARR_SBR: Annual rate of reduction in stillb...                       208   
CME_ARR_U5MR: Annual rate of reduction in under...                       231   
CME_MRM0: Neonatal mortality rate                                        239   
CME_MRY0: Infant mortality rate                                          239   
...                                                                      ...   
WS_SCH_W-B: Proportion of schools with basic dr...                       182   
WS_SCH_W-L: Proportion of schools with limited ...                       170   
WS_SCH_W-N: Proportion of schools with no drink...                       202   
WT_ADLS_15-19_ED_NEET: Percentage of adolescent...                       127   
WT_ADLS_15-19_LAB_FRC_UNEMP: Percentage of adol...                       188   

                                                    SEX:Sex  \
INDICATOR:Indicator                                           
CME_ARR_10T19: Annual Rate of Reduction in Mort...        1   
CME_ARR_SBR: Annual rate of reduction in stillb...        1   
CME_ARR_U5MR: Annual rate of reduction in under...        1   
CME_MRM0: Neonatal mortality rate                         1   
CME_MRY0: Infant mortality rate                           3   
...                                                     ...   
WS_SCH_W-B: Proportion of schools with basic dr...        1   
WS_SCH_W-L: Proportion of schools with limited ...        1   
WS_SCH_W-N: Proportion of schools with no drink...        1   
WT_ADLS_15-19_ED_NEET: Percentage of adolescent...        3   
WT_ADLS_15-19_LAB_FRC_UNEMP: Percentage of adol...        3   

                                                    TIME_PERIOD:Time period  \
INDICATOR:Indicator                                                           
CME_ARR_10T19: Annual Rate of Reduction in Mort...                        1   
CME_ARR_SBR: Annual rate of reduction in stillb...                        1   
CME_ARR_U5MR: Annual rate of reduction in under...                        1   
CME_MRM0: Neonatal mortality rate                                        70   
CME_MRY0: Infant mortality rate                                          87   
...                                                                     ...   
WS_SCH_W-B: Proportion of schools with basic dr...                       22   
WS_SCH_W-L: Proportion of schools with limited ...                       22   
WS_SCH_W-N: Proportion of schools with no drink...                       22   
WT_ADLS_15-19_ED_NEET: Percentage of adolescent...                       22   
WT_ADLS_15-19_LAB_FRC_UNEMP: Percentage of adol...                       12   

                                                    OBS_VALUE:Observation Value  \
INDICATOR:Indicator                                                               
CME_ARR_10T19: Annual Rate of Reduction in Mort...                           62   
CME_ARR_SBR: Annual rate of reduction in stillb...                          206  

In [8]:
CB_percent.groupby('SEX:Sex').nunique()

DATAFLOW  REF_AREA:Geographic area  INDICATOR:Indicator  \
SEX:Sex                                                              
F: Female         1                       298                  215   
M: Male           1                       298                  202   
_T: Total         1                       330                  357   

           TIME_PERIOD:Time period  OBS_VALUE:Observation Value  \
SEX:Sex                                                           
F: Female                      125                       234566   
M: Male                        125                       235140   
_T: Total                      162                       479137   

           UNIT_MULTIPLIER:Unit multiplier  UNIT_MEASURE:Unit of measure  \
SEX:Sex                                                                    
F: Female                                2                            17   
M: Male                                  2                            14   
_T: Total                                2                            21   

           OBS_STATUS:Observation Status  \
SEX:Sex                                    
F: Female                              8   
M: Male                                7   
_T: Total                              8   

           OBS_CONF:Observation confidentaility  LOWER_BOUND:Lower Bound  ...  \
SEX:Sex                                                                   ...   
F: Female                                     1                    73361  ...   
M: Male                                       1                    74783  ...   
_T: Total                                     2                   168580  ...   

           WGTD_SAMPL_SIZE:Weighted Sample Size  \
SEX:Sex                                           
F: Female                                  5549   
M: Male                                    5599   
_T: Total                                  7060   

           OBS_FOOTNOTE:Observation footnote  SERIES_FOOTNOTE:Series footnote  \
SEX:Sex                                                                         
F: Female                                497                                8   
M: Male                                  320                                8   
_T: Total                                780                               21   

           DATA_SOURCE:Data Source  \
SEX:Sex                              
F: Female                     3474   
M: Male                       1858   
_T: Total                     3646   

           SOURCE_LINK:Citation of or link to the data source  \
SEX:Sex                                                         
F: Female                                                 18    
M: Male                                                   14    
_T: Total                                                 47    

           CUSTODIAN:Custodian  \
SEX:Sex                          
F: Female                    3   
M: Male                      3   
_T: Total                    7   

           TIME_PERIOD_METHOD:Time period activity related to when the data are collected  \
SEX:Sex                                                                                     
F: Female                                                  3                                
M: Male                                                    3                                
_T: Total                                                  3                                

           REF_PERIOD:Reference Period  \
SEX:Sex                                  
F: Female                            0   
M: Male                              0   
_T: Total                            2   

           COVERAGE_TIME:The period of time for which data are provided  \
SEX:Sex                                                                   
F: Female                                                339              
M: Male                                                  319    

In [9]:
CB_percent.groupby('TIME_PERIOD:Time period').nunique()

DATAFLOW  REF_AREA:Geographic area  \
TIME_PERIOD:Time period                                       
1932                            1                         1   
1933                            1                         1   
1934                            1                         2   
1935                            1                         2   
1936                            1                         2   
...                           ...                       ...   
2020                            1                       321   
2020-04-16                      1                         1   
2020-12-11                      1                         1   
2021                            1                       300   
2022                            1                       255   

                         INDICATOR:Indicator  SEX:Sex  \
TIME_PERIOD:Time period                                 
1932                                       1        1   
1933                                       1        1   
1934                                       3        1   
1935                                       3        1   
1936                                       3        1   
...                                      ...      ...   
2020                                     299        3   
2020-04-16                                57        3   
2020-12-11                                57        3   
2021                                     189        3   
2022                                      30        3   

                         OBS_VALUE:Observation Value  \
TIME_PERIOD:Time period                                
1932                                               1   
1933                                               1   
1934                                               4   
1935                                               4   
1936                                               4   
...                                              ...   
2020                                           26524   
2020-04-16                                        97   
2020-12-11                                        79   
2021                                           12015   
2022                                            8653   

                         UNIT_MULTIPLIER:Unit multiplier  \
TIME_PERIOD:Time period                                    
1932                                                   0   
1933                                                   0   
1934                                                   0   
1935                                                   0   
1936                                                   0   
...                                                  ...   
2020                                                   2   
2020-04-16                                             1   
2020-12-11                                             1   
2021                                                   2   
2022                                                   2   

                         UNIT_MEASURE:Unit of measure  \
TIME_PERIOD:Time period                                 
1932                                                1   
1933                                                1   
1934                                                2   
1935                                                2   
1936                                                2   
...                                               ...   
2020                                               16   
2020-04-16                                          2   
2020-12-11                                          2   
2021                                               11   
2022                                                5   

                         OBS_STATUS:Observation Status  \
TIME_PERIOD:Time period                                  
1932                                                 1   
1933                                 

In [10]:
CB_percent.groupby('UNIT_MULTIPLIER:Unit multiplier').nunique()

DATAFLOW  REF_AREA:Geographic area  \
UNIT_MULTIPLIER:Unit multiplier                                       
0: Units                                1                       329   
3: Thousands                            1                       302   

                                 INDICATOR:Indicator  SEX:Sex  \
UNIT_MULTIPLIER:Unit multiplier                                 
0: Units                                         180        3   
3: Thousands                                      10        3   

                                 TIME_PERIOD:Time period  \
UNIT_MULTIPLIER:Unit multiplier                            
0: Units                                             145   
3: Thousands                                          73   

                                 OBS_VALUE:Observation Value  \
UNIT_MULTIPLIER:Unit multiplier                                
0: Units                                              197935   
3: Thousands                                          260504   

                                 UNIT_MEASURE:Unit of measure  \
UNIT_MULTIPLIER:Unit multiplier                                 
0: Units                                                   11   
3: Thousands                                                2   

                                 OBS_STATUS:Observation Status  \
UNIT_MULTIPLIER:Unit multiplier                                  
0: Units                                                     7   
3: Thousands                                                 2   

                                 OBS_CONF:Observation confidentaility  \
UNIT_MULTIPLIER:Unit multiplier                                         
0: Units                                                            1   
3: Thousands                                                        1   

                                 LOWER_BOUND:Lower Bound  ...  \
UNIT_MULTIPLIER:Unit multiplier                           ...   
0: Units                                            9716  ...   
3: Thousands                                        5677  ...   

                                 WGTD_SAMPL_SIZE:Weighted Sample Size  \
UNIT_MULTIPLIER:Unit multiplier                                         
0: Units                                                        16445   
3: Thousands                                                        0   

                                 OBS_FOOTNOTE:Observation footnote  \
UNIT_MULTIPLIER:Unit multiplier                                      
0: Units                                                       627   
3: Thousands                                                    21   

                                 SERIES_FOOTNOTE:Series footnote  \
UNIT_MULTIPLIER:Unit multiplier                                    
0: Units                                                      14   
3: Thousands                                                   4   

                                 DATA_SOURCE:Data Source  \
UNIT_MULTIPLIER:Unit multiplier                            
0: Units                                            4454   
3: Thousands                                           7   

                                 SOURCE_LINK:Citation of or link to the data source  \
UNIT_MULTIPLIER:Unit multiplier                                                       
0: Units                                                                        24    
3: Thousands                                                                     4    

                                 CUSTODIAN:Custodian  \
UNIT_MULTIPLIER:Unit multiplier                        
0: Units                                           7   
3: Thousands                                       2   

                                 TIME_PERIOD_METHOD:Time period activity related to when the data are collected  \
UNIT_MULTIPLIER:Unit multiplier                                                                                   
0: Units         

In [11]:
CB_percent.groupby('OBS_STATUS:Observation Status').nunique()

DATAFLOW  REF_AREA:Geographic area  \
OBS_STATUS:Observation Status                                       
A: Normal value                       1                       243   
AD: Adjusted                          1                       161   
E: Estimated value                    1                       288   
ER: External Reanalysis               1                        99   
MD: Modelled                          1                       253   
RA: Reanalysed                        1                       253   
RP: Reported                          1                       234   
U: Low reliability                    1                        32   

                               INDICATOR:Indicator  SEX:Sex  \
OBS_STATUS:Observation Status                                 
A: Normal value                                 39        3   
AD: Adjusted                                    18        3   
E: Estimated value                              78        3   
ER: External Reanalysis                         46        3   
MD: Modelled                                     9        2   
RA: Reanalysed                                 129        3   
RP: Reported                                   105        3   
U: Low reliability                              10        3   

                               TIME_PERIOD:Time period  \
OBS_STATUS:Observation Status                            
A: Normal value                                     90   
AD: Adjusted                                        39   
E: Estimated value                                  43   
ER: External Reanalysis                             34   
MD: Modelled                                        22   
RA: Reanalysed                                      97   
RP: Reported                                        43   
U: Low reliability                                  18   

                               OBS_VALUE:Observation Value  \
OBS_STATUS:Observation Status                                
A: Normal value                                     279319   
AD: Adjusted                                           513   
E: Estimated value                                   16730   
ER: External Reanalysis                                812   
MD: Modelled                                          4525   
RA: Reanalysed                                        2945   
RP: Reported                                          2592   
U: Low reliability                                     183   

                               UNIT_MULTIPLIER:Unit multiplier  \
OBS_STATUS:Observation Status                                    
A: Normal value                                              0   
AD: Adjusted                                                 1   
E: Estimated value                                           2   
ER: External Reanalysis                                      1   
MD: Modelled                                                 2   
RA: Reanalysed                                               1   
RP: Reported                                                 1   
U: Low reliability                                           1   

                               UNIT_MEASURE:Unit of measure  \
OBS_STATUS:Observation Status                                 
A: Normal value                                          11   
AD: Adjusted                                              1   
E: Estimated value                                        5   
ER: External Reanalysis                                   2   
MD: Modelled                                              4   
RA: Reanalysed                                            4   
RP: Reported                                              3   
U: Low reliability                                        1   

                               OBS_CONF:Observation confidentaility  \
OBS_STATUS:Observation Status                                         
A: Normal value                                                   0   
AD

In [12]:
CB_percent.groupby('OBS_CONF:Observation confidentaility').nunique()

DATAFLOW  \
OBS_CONF:Observation confidentaility                           
F: Free                                                    1   
N: Not for publication, restricted for internal...         1   

                                                    REF_AREA:Geographic area  \
OBS_CONF:Observation confidentaility                                           
F: Free                                                                  325   
N: Not for publication, restricted for internal...                       135   

                                                    INDICATOR:Indicator  \
OBS_CONF:Observation confidentaility                                      
F: Free                                                             194   
N: Not for publication, restricted for internal...                    2   

                                                    SEX:Sex  \
OBS_CONF:Observation confidentaility                          
F: Free                                                   3   
N: Not for publication, restricted for internal...        1   

                                                    TIME_PERIOD:Time period  \
OBS_CONF:Observation confidentaility                                          
F: Free                                                                 120   
N: Not for publication, restricted for internal...                       13   

                                                    OBS_VALUE:Observation Value  \
OBS_CONF:Observation confidentaility                                              
F: Free                                                                   23070   
N: Not for publication, restricted for internal...                          158   

                                                    UNIT_MULTIPLIER:Unit multiplier  \
OBS_CONF:Observation confidentaility                                                  
F: Free                                                                           2   
N: Not for publication, restricted for internal...                                0   

                                                    UNIT_MEASURE:Unit of measure  \
OBS_CONF:Observation confidentaility                                               
F: Free                                                                        8   
N: Not for publication, restricted for internal...                             1   

                                                    OBS_STATUS:Observation Status  \
OBS_CONF:Observation confidentaility                                                
F: Free                                                                         7   
N: Not for publication, restricted for internal...                              2   

                                                    LOWER_BOUND:Lower Bound  \
OBS_CONF:Observation confidentaility                                          
F: Free                                                               14495   
N: Not for publication, restricted for internal...                        0   

                                                    ...  \
OBS_CONF:Observation confidentaility                ...   
F: Free                                             ...   
N: Not for publication, restricted for internal...  ...   

                                                    WGTD_SAMPL_SIZE:Weighted Sample Size  \
OBS_CONF:Observation confidentaility                                                       
F: Free                                                                            16445   
N: Not for publication, restricted for internal...                                     0   

                                                    OBS_FOOTNOTE:Observation footnote  \
OBS_CONF:Observation confidentaility                                                    
F: Free                                                                          1007   
N: Not for publication, restricted for internal...   

In [13]:
CB_percent.groupby('LOWER_BOUND:Lower Bound').nunique()

DATAFLOW  REF_AREA:Geographic area  \
LOWER_BOUND:Lower Bound                                       
-0.0                            1                        58   
-0.1                            1                        63   
-0.2                            1                        74   
-0.3                            1                        78   
-0.4                            1                        80   
...                           ...                       ...   
<1                              1                        88   
<100                            1                       124   
<200                            1                       120   
<500                            1                       123   
>95                             1                        17   

                         INDICATOR:Indicator  SEX:Sex  \
LOWER_BOUND:Lower Bound                                 
-0.0                                       4        3   
-0.1                                       5        3   
-0.2                                       5        3   
-0.3                                       5        3   
-0.4                                       5        3   
...                                      ...      ...   
<1                                         4        1   
<100                                       7        3   
<200                                       7        3   
<500                                       7        3   
>95                                        4        1   

                         TIME_PERIOD:Time period  OBS_VALUE:Observation Value  \
LOWER_BOUND:Lower Bound                                                         
-0.0                                          33                            6   
-0.1                                          41                            6   
-0.2                                          46                           10   
-0.3                                          49                            5   
-0.4                                          44                            7   
...                                          ...                          ...   
<1                                            21                            9   
<100                                          21                           11   
<200                                          21                           52   
<500                                          21                           73   
>95                                           20                            1   

                         UNIT_MULTIPLIER:Unit multiplier  \
LOWER_BOUND:Lower Bound                                    
-0.0                                                   1   
-0.1                                                   1   
-0.2                                                   1   
-0.3                                                   2   
-0.4                                                   1   
...                                                  ...   
<1                                                     1   
<100                                                   1   
<200                                                   1   
<500                                                   1   
>95                                                    1   

                         UNIT_MEASURE:Unit of measure  \
LOWER_BOUND:Lower Bound                                 
-0.0                                                1   
-0.1                                                2   
-0.2                                                2   
-0.3                                                1   
-0.4                                                2   
...                                               ...   
<1                                                  1   
<100                                                1   
<200                                                1   
<

In [14]:
CB_percent.groupby('UPPER_BOUND:Upper Bound').nunique()

DATAFLOW  REF_AREA:Geographic area  \
UPPER_BOUND:Upper Bound                                       
-0.0                            1                        52   
-0.1                            1                        69   
-0.2                            1                        67   
-0.3                            1                        71   
-0.4                            1                        69   
...                           ...                       ...   
<1                              1                        86   
<100                            1                       107   
<200                            1                       114   
<500                            1                       114   
>95                             1                        71   

                         INDICATOR:Indicator  SEX:Sex  \
UPPER_BOUND:Upper Bound                                 
-0.0                                       4        3   
-0.1                                       4        3   
-0.2                                       4        3   
-0.3                                       4        3   
-0.4                                       4        3   
...                                      ...      ...   
<1                                         4        1   
<100                                       7        3   
<200                                       7        3   
<500                                       7        3   
>95                                        4        1   

                         TIME_PERIOD:Time period  OBS_VALUE:Observation Value  \
UPPER_BOUND:Upper Bound                                                         
-0.0                                          34                            3   
-0.1                                          48                            4   
-0.2                                          47                            4   
-0.3                                          44                            3   
-0.4                                          45                            5   
...                                          ...                          ...   
<1                                            18                            1   
<100                                          21                            1   
<200                                          21                            2   
<500                                          21                            3   
>95                                           21                          214   

                         UNIT_MULTIPLIER:Unit multiplier  \
UPPER_BOUND:Upper Bound                                    
-0.0                                                   1   
-0.1                                                   1   
-0.2                                                   1   
-0.3                                                   1   
-0.4                                                   1   
...                                                  ...   
<1                                                     1   
<100                                                   1   
<200                                                   1   
<500                                                   1   
>95                                                    1   

                         UNIT_MEASURE:Unit of measure  \
UPPER_BOUND:Upper Bound                                 
-0.0                                                1   
-0.1                                                1   
-0.2                                                1   
-0.3                                                1   
-0.4                                                1   
...                                               ...   
<1                                                  1   
<100                                                1   
<200                                                1   
<

In [15]:
CB_percent.groupby('WGTD_SAMPL_SIZE:Weighted Sample Size').nunique()

DATAFLOW  REF_AREA:Geographic area  \
WGTD_SAMPL_SIZE:Weighted Sample Size                                       
0.000000e+00                                 1                         1   
2.000000e-01                                 1                         1   
3.000000e-01                                 1                         1   
4.000000e-01                                 1                         1   
5.000000e-01                                 1                         1   
...                                        ...                       ...   
2.360556e+12                                 1                         1   
2.361127e+12                                 1                         1   
2.364772e+12                                 1                         1   
2.377285e+12                                 1                         1   
2.431224e+12                                 1                         1   

                                      INDICATOR:Indicator  SEX:Sex  \
WGTD_SAMPL_SIZE:Weighted Sample Size                                 
0.000000e+00                                            2        1   
2.000000e-01                                            1        1   
3.000000e-01                                            3        2   
4.000000e-01                                            3        2   
5.000000e-01                                            3        2   
...                                                   ...      ...   
2.360556e+12                                            9        1   
2.361127e+12                                           11        1   
2.364772e+12                                           11        1   
2.377285e+12                                           11        1   
2.431224e+12                                           11        1   

                                      TIME_PERIOD:Time period  \
WGTD_SAMPL_SIZE:Weighted Sample Size                            
0.000000e+00                                                1   
2.000000e-01                                                1   
3.000000e-01                                                1   
4.000000e-01                                                1   
5.000000e-01                                                1   
...                                                       ...   
2.360556e+12                                                1   
2.361127e+12                                                1   
2.364772e+12                                                1   
2.377285e+12                                                1   
2.431224e+12                                                1   

                                      OBS_VALUE:Observation Value  \
WGTD_SAMPL_SIZE:Weighted Sample Size                                
0.000000e+00                                                    2   
2.000000e-01                                                    1   
3.000000e-01                                                    4   
4.000000e-01                                                    3   
5.000000e-01                                                    3   
...                                                           ...   
2.360556e+12                                                    8   
2.361127e+12                                                    9   
2.364772e+12                                                   10   
2.377285e+12                                                   10   
2.431224e+12                                                    8   

                                      UNIT_MULTIPLIER:Unit multiplier  \
WGTD_SAMPL_SIZE:Weighted Sample Size                                    
0.000000e+00                                                        1   
2.000000e-01                                                        1   
3.000000e-01                                                        1   
4.000000e-01                 

In [16]:
CB_percent.groupby('OBS_FOOTNOTE:Observation footnote').nunique()

DATAFLOW  \
OBS_FOOTNOTE:Observation footnote                              
-Break in series-Break in series: Methodology r...         1   
-Break in series-Break in series: Methodology r...         1   
-Break in series-Break in series: Methodology r...         1   
-Break in series-Break in series: Methodology r...         1   
-Break in series-Break in series: Methodology r...         1   
...                                                      ...   
regional average is based only on United States...         1   
regional average is based only on United States...         1   
y                                                          1   
ÃÂ¢Ã¢ÂÂ°ÃÂ¥5ppm                                         1   
ÃÂ¢Ã¢ÂÂ°ÃÂ¥5ppm  Obtained from Knowles JM  G...         1   

                                                    REF_AREA:Geographic area  \
OBS_FOOTNOTE:Observation footnote                                              
-Break in series-Break in series: Methodology r...                         1   
-Break in series-Break in series: Methodology r...                         2   
-Break in series-Break in series: Methodology r...                         2   
-Break in series-Break in series: Methodology r...                         1   
-Break in series-Break in series: Methodology r...                         1   
...                                                                      ...   
regional average is based only on United States...                         2   
regional average is based only on United States...                         2   
y                                                                          1   
ÃÂ¢Ã¢ÂÂ°ÃÂ¥5ppm                                                         4   
ÃÂ¢Ã¢ÂÂ°ÃÂ¥5ppm  Obtained from Knowles JM  G...                         1   

                                                    INDICATOR:Indicator  \
OBS_FOOTNOTE:Observation footnote                                         
-Break in series-Break in series: Methodology r...                    1   
-Break in series-Break in series: Methodology r...                    1   
-Break in series-Break in series: Methodology r...                    1   
-Break in series-Break in series: Methodology r...                    1   
-Break in series-Break in series: Methodology r...                    1   
...                                                                 ...   
regional average is based only on United States...                    1   
regional average is based only on United States...                    3   
y                                                                     1   
ÃÂ¢Ã¢ÂÂ°ÃÂ¥5ppm                                                    2   
ÃÂ¢Ã¢ÂÂ°ÃÂ¥5ppm  Obtained from Knowles JM  G...                    1   

                                                    SEX:Sex  \
OBS_FOOTNOTE:Observation footnote                             
-Break in series-Break in series: Methodology r...        3   
-Break in series-Break in series: Methodology r...        3   
-Break in series-Break in series: Methodology r...        3   
-Break in series-Break in series: Methodology r...        3   
-Break in series-Break in series: Methodology r...        3   
...                                                     ...   
regional average is based only on United States...        1   
regional average is based only on United States...        1   
y                                                         3   
ÃÂ¢Ã¢ÂÂ°ÃÂ¥5ppm                                        1   
ÃÂ¢Ã¢ÂÂ°ÃÂ¥5ppm  Obtained from Knowles JM  G...        1   

                                                    TIME_PERIOD:Time period  \
OBS_FOOTNOTE:Observation footnote                                             
-Break in series-Break in series: Methodology r...                        1   
-Break in series-Break in series: Methodology r...                        1   
-Break in series-Break in series: Methodology r...                

In [17]:
CB_percent.groupby('SERIES_FOOTNOTE:Series footnote').nunique()

DATAFLOW  \
SERIES_FOOTNOTE:Series footnote                                
233 countries from WUP2018, used WPP2019 total ...         1   
Consumption                                                1   
Data from 236 countries/areas with population m...         1   
Data from 237 countries/areas from WPP2022                 1   
Data from Global AIDS Monitoring and UNAIDS est...         1   
Earnings                                                   1   
Expressed in Current US Dollars                            1   
Global UNICEF Global Databases: Infant and Youn...         1   
Income (gross)                                             1   
Income (net)                                               1   
Income (net/gross)                                         1   
NCD-RisC. Worldwide trends in body-mass index  ...         1   
UNICEF Global Databases on Iodized salt  New Yo...         1   
UNICEF Global Infant and Young Child Feeding Da...         1   
UNICEF global database on births without a birt...         1   
UNICEF global databases  2021  based on adminis...         1   
UNICEF-WHO Low birthweight estimates 2019                  1   
UNICEF/WHO/World Bank Joint Malnutrition Estima...         1   
based on GDP                                               1   
based on ln(Pt/P0) / t (and then expressed in p...         1   
based on ln(Pt/P0) / t (and then expressed in p...         1   

                                                    REF_AREA:Geographic area  \
SERIES_FOOTNOTE:Series footnote                                                
233 countries from WUP2018, used WPP2019 total ...                       243   
Consumption                                                              103   
Data from 236 countries/areas with population m...                       251   
Data from 237 countries/areas from WPP2022                               252   
Data from Global AIDS Monitoring and UNAIDS est...                       160   
Earnings                                                                   3   
Expressed in Current US Dollars                                          226   
Global UNICEF Global Databases: Infant and Youn...                       124   
Income (gross)                                                             6   
Income (net)                                                              58   
Income (net/gross)                                                        32   
NCD-RisC. Worldwide trends in body-mass index  ...                       190   
UNICEF Global Databases on Iodized salt  New Yo...                       150   
UNICEF Global Infant and Young Child Feeding Da...                       199   
UNICEF global database on births without a birt...                       178   
UNICEF global databases  2021  based on adminis...                        64   
UNICEF-WHO Low birthweight estimates 2019                                214   
UNICEF/WHO/World Bank Joint Malnutrition Estima...                       223   
based on GDP                                                             165   
based on ln(Pt/P0) / t (and then expressed in p...                       251   
based on ln(Pt/P0) / t (and then expressed in p...                       241   

                                                    INDICATOR:Indicator  \
SERIES_FOOTNOTE:Series footnote                                           
233 countries from WUP2018, used WPP2019 total ...                    1   
Consumption                                                           2   
Data from 236 countries/areas with population m...                    9   
Data from 237 countries/areas from WPP2022                            4   
Data from Global AIDS Monitoring and UNAIDS est...                   23   
Earnings                                                              2   
Expressed in Current US Dollars                                       1   
Global UNICEF Global Databases: Infant and Youn...             

In [18]:
CB_percent.groupby('DATA_SOURCE:Data Source').nunique()

DATAFLOW  \
DATA_SOURCE:Data Source                                        
 Brazil National Survey on Health and Nutrition...         1   
 Cambodia Demographic and Health Survey 2014. P...         1   
 Dirección General de Estadística  Encuestas y ...         1   
 Dominican Republic National Multipurpose House...         1   
 EnquÃÂÃÂªte DÃÂÃÂ©mographique et de Sant...         1   
...                                                      ...   
n Institute for Public Health 2018                         1   
n National HIV Prevalence; Incidence; Behaviour...         1   
ÃÂÃ¢ÂÂ°tude epidemiologique de la lutte cont...         1   
Évaluation finale Quatrième Round du Fonds mond...         1   
Česky Statistický úřad  Odbor statistiky obyvat...         1   

                                                    REF_AREA:Geographic area  \
DATA_SOURCE:Data Source                                                        
 Brazil National Survey on Health and Nutrition...                         1   
 Cambodia Demographic and Health Survey 2014. P...                         1   
 Dirección General de Estadística  Encuestas y ...                         1   
 Dominican Republic National Multipurpose House...                         1   
 EnquÃÂÃÂªte DÃÂÃÂ©mographique et de Sant...                         1   
...                                                                      ...   
n Institute for Public Health 2018                                         1   
n National HIV Prevalence; Incidence; Behaviour...                         1   
ÃÂÃ¢ÂÂ°tude epidemiologique de la lutte cont...                         1   
Évaluation finale Quatrième Round du Fonds mond...                         1   
Česky Statistický úřad  Odbor statistiky obyvat...                         1   

                                                    INDICATOR:Indicator  \
DATA_SOURCE:Data Source                                                   
 Brazil National Survey on Health and Nutrition...                   57   
 Cambodia Demographic and Health Survey 2014. P...                   24   
 Dirección General de Estadística  Encuestas y ...                    1   
 Dominican Republic National Multipurpose House...                    3   
 EnquÃÂÃÂªte DÃÂÃÂ©mographique et de Sant...                    2   
...                                                                 ...   
n Institute for Public Health 2018                                    2   
n National HIV Prevalence; Incidence; Behaviour...                    3   
ÃÂÃ¢ÂÂ°tude epidemiologique de la lutte cont...                    2   
Évaluation finale Quatrième Round du Fonds mond...                    1   
Česky Statistický úřad  Odbor statistiky obyvat...                    1   

                                                    SEX:Sex  \
DATA_SOURCE:Data Source                                       
 Brazil National Survey on Health and Nutrition...        3   
 Cambodia Demographic and Health Survey 2014. P...        3   
 Dirección General de Estadística  Encuestas y ...        1   
 Dominican Republic National Multipurpose House...        3   
 EnquÃÂÃÂªte DÃÂÃÂ©mographique et de Sant...        1   
...                                                     ...   
n Institute for Public Health 2018                        2   
n National HIV Prevalence; Incidence; Behaviour...        2   
ÃÂÃ¢ÂÂ°tude epidemiologique de la lutte cont...        1   
Évaluation finale Quatrième Round du Fonds mond...        1   
Česky Statistický úřad  Odbor statistiky obyvat...        1   

                                                    TIME_PERIOD:Time period  \
DATA_SOURCE:Data Source                                                       
 Brazil National Survey on Health and Nutrition...                        1   
 Cambodia Demographic and Health Survey 2014. P...                        1   
 Dirección General de Estadística  Encuestas y ...                

In [19]:
CB_percent.groupby('SOURCE_LINK:Citation of or link to the data source').nunique()

DATAFLOW  \
SOURCE_LINK:Citation of or link to the data source             
CRAVE 2020 Addition                                        1   
Data downloaded from SDG Database October 2022             1   
Data downloaded from United Nations, Department...         1   
Data downloaded from WHO MNCAH Data Portal Sept...         1   
Data downloaded from WHO MNCAH Data Portal, htt...         1   
Data downloaded from WHO MNCAH Data Portal, htt...         1   
Ever-married women age 20-24                               1   
Joint UNICEF-WHO Database on Skilled Birth Atte...         1   
Mali 2015 MICS Final Report - Errata November 2017         1   
Re-analysed based on the old DHS definition                1   
Re-analysed value (2017)                                   1   
Statcompiler                                               1   
United Nations, Department of Economic and Soci...         1   
http://200.41.235.179:83/images/documentos/otra...         1   
http://aidsinfo.unaids.org/                                1   
http://diepresse.com/home/bildung/erziehung/584...         1   
http://gender.gov.mv/en/?p=4346                            1   
http://proyectos.inei.gob.pe/web/biblioineipub/...         1   
http://smslap.ditjenpas.go.id/public/grl/curren...         1   
http://www.acf.hhs.gov/sites/default/files/cb/a...         1   
http://www.aifs.gov.au/cfca/pubs/factsheets/a14...         1   
http://www.childrenportal.belstat.gov.by/ ind.#161         1   
http://www.cna.gob.gt/docs/site/ML2015.pdf                 1   
http://www.dohc.ie/publications/pdf/KeyTrends_2...         1   
http://www.eurochild.org/fileadmin/user_upload/...         1   
http://www.hrw.org/sites/default/files/reports/...         1   
http://www.mca.gov.cn/article/sj/tjgb/                     1   
http://www.msd.govt.nz/documents/about-msd-and-...         1   
https://court.gov.ua/userfiles/media/new_folder...         1   
https://data.unicef.org/topic/nutrition/infant-...         1   
https://data.unicef.org/topic/nutrition/infant-...         1   
https://data.unicef.org/topic/nutrition/iodine/            1   
https://data.unicef.org/topic/nutrition/low-bir...         1   
https://data.unicef.org/topic/nutrition/malnutr...         1   
https://dataunodc.un.org/data/Prison/Persons%20...         1   
https://ec.europa.eu/eurostat/databrowser/view/...         1   
https://ec.europa.eu/eurostat/databrowser/view/...         1   
https://msmps.gov.md/wp-content/uploads/2021/06...         1   
https://ncdrisc.org/                                       1   
https://paidi.gov.gr/wp-content/uploads/2022/01...         1   
https://population.un.org/wpp/                             1   
https://population.un.org/wup/                             1   
https://www.destatis.de/DE/ZahlenFakten/Gesells...         1   
https://www.inau.gub.uy/estudios-de-poblacion-y...         1   
https://www.inegi.org.mx/contenidos/programas/c...         1   
https://www.inegi.org.mx/programas/cngspspe/202...         1   
https://www.internal-displacement.org/database/...         1   
https://www.justice.gov.za/vg/cj/IND-ANR-2019-2...         1   
https://www.stat.gov.az/menu/6/statistical_year...         1   
https://www.un.org/development/desa/pd/content/...         1   
https://www.unhcr.org/refugee-statistics/download/         1   

                                                    REF_AREA:Geographic area  \
SOURCE_LINK:Citation of or link to the data source                             
CRAVE 2020 Addition                                                        1   
Data downloaded from SDG Database October 2022                           216   
Data downloaded from United Nations, Department...                       232   
Data downloaded from WHO MNCAH Data Portal Sept...                       126   
Data downloaded from WHO MNCAH Data Portal, htt...                       133   
Data downloaded from WHO MNCAH Data Portal, htt...                       189   
Ever-married women 

In [20]:
CB_percent.groupby('CUSTODIAN:Custodian').nunique()

DATAFLOW  \
CUSTODIAN:Custodian                                            
NCD Risk Factor Collaboration                              1   
Nutrition Section  Programme Dvision and the Da...         1   
UNICEF                                                     1   
UNICEF Division of Data  Analysis  Planning and...         1   
UNICEF Division of Data  Analysis  Planning and...         1   
UNICEF Division of Data, Analysis, Planning and...         1   
UNICEF WHO                                                 1   

                                                    REF_AREA:Geographic area  \
CUSTODIAN:Custodian                                                            
NCD Risk Factor Collaboration                                            190   
Nutrition Section  Programme Dvision and the Da...                        64   
UNICEF                                                                   178   
UNICEF Division of Data  Analysis  Planning and...                       229   
UNICEF Division of Data  Analysis  Planning and...                       214   
UNICEF Division of Data, Analysis, Planning and...                       124   
UNICEF WHO                                                               147   

                                                    INDICATOR:Indicator  \
CUSTODIAN:Custodian                                                       
NCD Risk Factor Collaboration                                         2   
Nutrition Section  Programme Dvision and the Da...                    3   
UNICEF                                                                1   
UNICEF Division of Data  Analysis  Planning and...                   85   
UNICEF Division of Data  Analysis  Planning and...                    2   
UNICEF Division of Data, Analysis, Planning and...                    1   
UNICEF WHO                                                            1   

                                                    SEX:Sex  \
CUSTODIAN:Custodian                                           
NCD Risk Factor Collaboration                             3   
Nutrition Section  Programme Dvision and the Da...        1   
UNICEF                                                    1   
UNICEF Division of Data  Analysis  Planning and...        3   
UNICEF Division of Data  Analysis  Planning and...        1   
UNICEF Division of Data, Analysis, Planning and...        3   
UNICEF WHO                                                1   

                                                    TIME_PERIOD:Time period  \
CUSTODIAN:Custodian                                                           
NCD Risk Factor Collaboration                                            42   
Nutrition Section  Programme Dvision and the Da...                       21   
UNICEF                                                                   15   
UNICEF Division of Data  Analysis  Planning and...                      109   
UNICEF Division of Data  Analysis  Planning and...                       16   
UNICEF Division of Data, Analysis, Planning and...                       30   
UNICEF WHO                                                               16   

                                                    OBS_VALUE:Observation Value  \
CUSTODIAN:Custodian                                                               
NCD Risk Factor Collaboration                                               620   
Nutrition Section  Programme Dvision and the Da...                          100   
UNICEF                                                                      125   
UNICEF Division of Data  Analysis  Planning and...                         5950   
UNICEF Division of Data  Analysis  Planning and...                         1805   
UNICEF Division of Data, Analysis, Planning and...                         1021   
UNICEF WHO                                                                  232   

                                                  

In [21]:
CB_percent.groupby('TIME_PERIOD_METHOD:Time period activity related to when the data are collected').nunique()

DATAFLOW  \
TIME_PERIOD_METHOD:Time period activity related...             
EOF: End of fieldwork                                      1   
MOF: Middle of fieldwork                                   1   
OTHER: Other                                               1   

                                                    REF_AREA:Geographic area  \
TIME_PERIOD_METHOD:Time period activity related...                             
EOF: End of fieldwork                                                    288   
MOF: Middle of fieldwork                                                 162   
OTHER: Other                                                             262   

                                                    INDICATOR:Indicator  \
TIME_PERIOD_METHOD:Time period activity related...                        
EOF: End of fieldwork                                                58   
MOF: Middle of fieldwork                                             82   
OTHER: Other                                                         29   

                                                    SEX:Sex  \
TIME_PERIOD_METHOD:Time period activity related...            
EOF: End of fieldwork                                     3   
MOF: Middle of fieldwork                                  3   
OTHER: Other                                              3   

                                                    TIME_PERIOD:Time period  \
TIME_PERIOD_METHOD:Time period activity related...                            
EOF: End of fieldwork                                                    25   
MOF: Middle of fieldwork                                                109   
OTHER: Other                                                             46   

                                                    OBS_VALUE:Observation Value  \
TIME_PERIOD_METHOD:Time period activity related...                                
EOF: End of fieldwork                                                      9269   
MOF: Middle of fieldwork                                                   1988   
OTHER: Other                                                               6814   

                                                    UNIT_MULTIPLIER:Unit multiplier  \
TIME_PERIOD_METHOD:Time period activity related...                                    
EOF: End of fieldwork                                                             1   
MOF: Middle of fieldwork                                                          1   
OTHER: Other                                                                      2   

                                                    UNIT_MEASURE:Unit of measure  \
TIME_PERIOD_METHOD:Time period activity related...                                 
EOF: End of fieldwork                                                          3   
MOF: Middle of fieldwork                                                       2   
OTHER: Other                                                                   2   

                                                    OBS_STATUS:Observation Status  \
TIME_PERIOD_METHOD:Time period activity related...                                  
EOF: End of fieldwork                                                           4   
MOF: Middle of fieldwork                                                        5   
OTHER: Other                                                                    5   

                                                    OBS_CONF:Observation confidentaility  \
TIME_PERIOD_METHOD:Time period activity related...                                         
EOF: End of fieldwork                                                                  2   
MOF: Middle of fieldwork                                                               1   
OTHER: Other                                                                           1   

                                                    ...  \
TIME_PERIOD_METHOD:Time

In [22]:
CB_percent.groupby('REF_PERIOD:Reference Period').nunique()

DATAFLOW  REF_AREA:Geographic area  \
REF_PERIOD:Reference Period                                       
2000-2019                           1                       195   
2000-2020                           1                       231   

                             INDICATOR:Indicator  SEX:Sex  \
REF_PERIOD:Reference Period                                 
2000-2019                                      1        1   
2000-2020                                      2        1   

                             TIME_PERIOD:Time period  \
REF_PERIOD:Reference Period                            
2000-2019                                          1   
2000-2020                                          2   

                             OBS_VALUE:Observation Value  \
REF_PERIOD:Reference Period                                
2000-2019                                            195   
2000-2020                                             89   

                             UNIT_MULTIPLIER:Unit multiplier  \
REF_PERIOD:Reference Period                                    
2000-2019                                                  0   
2000-2020                                                  0   

                             UNIT_MEASURE:Unit of measure  \
REF_PERIOD:Reference Period                                 
2000-2019                                               1   
2000-2020                                               1   

                             OBS_STATUS:Observation Status  \
REF_PERIOD:Reference Period                                  
2000-2019                                                1   
2000-2020                                                1   

                             OBS_CONF:Observation confidentaility  ...  \
REF_PERIOD:Reference Period                                        ...   
2000-2019                                                       0  ...   
2000-2020                                                       0  ...   

                             UPPER_BOUND:Upper Bound  \
REF_PERIOD:Reference Period                            
2000-2019                                          0   
2000-2020                                         80   

                             WGTD_SAMPL_SIZE:Weighted Sample Size  \
REF_PERIOD:Reference Period                                         
2000-2019                                                       0   
2000-2020                                                       0   

                             OBS_FOOTNOTE:Observation footnote  \
REF_PERIOD:Reference Period                                      
2000-2019                                                    0   
2000-2020                                                    0   

                             SERIES_FOOTNOTE:Series footnote  \
REF_PERIOD:Reference Period                                    
2000-2019                                                  0   
2000-2020                                                  0   

                             DATA_SOURCE:Data Source  \
REF_PERIOD:Reference Period                            
2000-2019                                          1   
2000-2020                                          1   

                             SOURCE_LINK:Citation of or link to the data source  \
REF_PERIOD:Reference Period                                                       
2000-2019                                                                    0    
2000-2020                                                                    0    

                             CUSTODIAN:Custodian  \
REF_PERIOD:Reference Period                        
2000-2019                                      0   
2000-2020                                      0   

                             TIME_PERIOD_METHOD:Time period activity related to when the data are collected  \
REF_PERIOD:Reference Period                                                                        

In [23]:
CB_percent.groupby('COVERAGE_TIME:The period of time for which data are provided').nunique()

DATAFLOW  \
COVERAGE_TIME:The period of time for which data...             
1975-2016                                                  1   
1983-2010                                                  1   
1985-1994                                                  1   
1985-1995                                                  1   
1985-2018                                                  1   
...                                                      ...   
2020-2030                                                  1   
2020-21                                                    1   
2021                                                       1   
2022                                                       1   
NA-NA                                                      1   

                                                    REF_AREA:Geographic area  \
COVERAGE_TIME:The period of time for which data...                             
1975-2016                                                                190   
1983-2010                                                                  1   
1985-1994                                                                  1   
1985-1995                                                                  1   
1985-2018                                                                  1   
...                                                                      ...   
2020-2030                                                                253   
2020-21                                                                    1   
2021                                                                     253   
2022                                                                       1   
NA-NA                                                                      4   

                                                    INDICATOR:Indicator  \
COVERAGE_TIME:The period of time for which data...                        
1975-2016                                                             2   
1983-2010                                                             5   
1985-1994                                                             3   
1985-1995                                                             4   
1985-2018                                                             4   
...                                                                 ...   
2020-2030                                                             2   
2020-21                                                               2   
2021                                                                 26   
2022                                                                  1   
NA-NA                                                                 2   

                                                    SEX:Sex  \
COVERAGE_TIME:The period of time for which data...            
1975-2016                                                 3   
1983-2010                                                 3   
1985-1994                                                 1   
1985-1995                                                 1   
1985-2018                                                 3   
...                                                     ...   
2020-2030                                                 3   
2020-21                                                   3   
2021                                                      3   
2022                                                      1   
NA-NA                                                     3   

                                                    TIME_PERIOD:Time period  \
COVERAGE_TIME:The period of time for which data...                            
1975-2016                                                                42   
1983-2010                                                                 3   
1985-1994                                                         

In [24]:
CB_percent.groupby('AGE:Current age').nunique()

DATAFLOW  REF_AREA:Geographic area  \
AGE:Current age                                                     
M0T23: Under 24 months old            1                       179   
M0T47: Under 48 months old            1                         2   
M0T5: Under 6 months old              1                       189   
M12T15: 12 to 15 months old           1                       132   
M12T23: 12 to 23 months old           1                       256   
M20T23: 20 to 23 months old           1                       131   
M24T59: 24 to 59 months old           1                        51   
M36T59: 36 to 59 months old           1                       113   
M6T23: 6 to 23 months old             1                       174   
M6T59: 6 to 59 months old             1                        64   
Y0: Under 1 year old                  1                       205   
Y0T14: Under 15 years old             1                        30   
Y0T17: Under 18 years old             1                       250   
Y0T4: Under 5 years old               1                       270   
Y10T14: 10 to 14 years old            1                       238   
Y10T19: 10 to 19 years old            1                       194   
Y11T17: 11 to 17 years old            1                       175   
Y13T15: 13 to 15 years                1                       194   
Y14T17: 14 to 17 years old            1                        43   
Y15T19: 15 to 19 years old            1                       256   
Y15T24: 15 to 24 years old            1                        78   
Y15T49: 15 to 49 years old            1                       253   
Y18T29: 18 to 29 years old            1                        64   
Y1T14: 1 to 14 years old              1                        95   
Y20T24: 20 to 24 years old            1                       177   
Y5T17: 5 to 17 years old              1                        82   
Y_GE15: 15 years old and over         1                       192   
Y_GE25: 25 years old and over         1                       109   
_T: Total                             1                       329   

                               INDICATOR:Indicator  SEX:Sex  \
AGE:Current age                                               
M0T23: Under 24 months old                       2        3   
M0T47: Under 48 months old                       3        3   
M0T5: Under 6 months old                         3        3   
M12T15: 12 to 15 months old                      1        3   
M12T23: 12 to 23 months old                     12        3   
M20T23: 20 to 23 months old                      1        3   
M24T59: 24 to 59 months old                      1        3   
M36T59: 36 to 59 months old                      2        3   
M6T23: 6 to 23 months old                       14        3   
M6T59: 6 to 59 months old                        3        1   
Y0: Under 1 year old                             5        1   
Y0T14: Under 15 years old                        1        1   
Y0T17: Under 18 years old                        6        1   
Y0T4: Under 5 years old                         72        3   
Y10T14: 10 to 14 years old                       2        2   
Y10T19: 10 to 19 years old                       4        3   
Y11T17: 11 to 17 years old                       1        3   
Y13T15: 13 to 15 years                           2        3   
Y14T17: 14 to 17 years old                       1        1   
Y15T19: 15 to 19 years old                       4        3   
Y15T24: 15 to 24 years old                       4        3   
Y15T49: 15 to 49 years old                      16        3   
Y18T29: 18 to 29 years old                       2        1   
Y1T14: 1 to 14 years old                         1        3   
Y20T24: 20 to 24 years old                       3        2   
Y5T17: 5 to 17 years old                         1        3   
Y_GE15: 15 years old and over                    3        3   
Y_GE25: 25 years old and over                    1        2   
_

- `DATAFLOW` column has only one value, which has no added value for our project, hence can be dropped from the original data set.
- `REF_AREA:Geographic area` column contains 330 differenc geographical areas (ie. countries) which is one of the main coulumns we expected to find.
- `INDICATOR:Indicator` column lists different indicators that data represents. There are 380 unique values.  
- `SEX:Sex` column indicate if the figures collected reffer to *F: Female*, *M: Male* or *_T: Total*. Something I'm not focusing to look into at this moment, hence decision to look at only *_T: Total* values.
- `TIME_PERIOD:Time period` column indicates year the data is reported for, but it was noticed that some fields don't only contain just a year, but also a specific dates. This needs further analysis and filtering.
- `UNIT_MULTIPLIER:Unit multiplier`column indicates if data represents *0: Units* or *3: Thousands*.
- `OBS_STATUS:Observation Status` column has 8 unique values describing how the values were obtained. I have decided to discard all rows that are not having *A: Normal value* or *RP: Reported* values.
- `OBS_CONF:Observation confidentaility`column indicates if data is *F: Free* or *N: Not for publication, restricted for internal use only*.
- `LOWER_BOUND:Lower Bound` contains 289582 different values. 
- `UPPER_BOUND:Upper Bound` contains 297085 different values.
- `WGTD_SAMPL_SIZE:Weighted Sample Size` contains 16445 different values.
- `OBS_FOOTNOTE:Observation footnote` contains 1037 different notes about the data points.
- `SERIES_FOOTNOTE:Series footnote`  contains 21 different values and provides some additional note about the data points
- `DATA_SOURCE:Data Source` contains 5007 different references on where is data coming from and it looks it's mainly written in the local language.
- `SOURCE_LINK:Citation of or link to the data source` column name is self explanatory and contas 51 unique values
- `CUSTODIAN:Custodian` column contains information about 7 different data custodians.
- `TIME_PERIOD_METHOD:Time period activity related to when the data are collected` column has 3 unique values *EOF: End of fieldwork*,  *MOF: Middle of fieldwork* and *OTHER: Other* which doesn't seem too interesting hence will drop from the final data set. 
- `REF_PERIOD:Reference Period` column contains two unique values *2000-2019* and *2000-2020*
- `COVERAGE_TIME:The period of time for which data are provided` column contains 377 unique values for the time period data points are provided.
- `AGE:Current age` column indicates the age range of population counted and contains 29 unique values. 

Analyzing `INDICATOR:Indicator` column

In [25]:
CB_Ind = CB_percent.groupby('INDICATOR:Indicator').nunique()
CB_Ind

DATAFLOW  \
INDICATOR:Indicator                                            
CME_ARR_10T19: Annual Rate of Reduction in Mort...         1   
CME_ARR_SBR: Annual rate of reduction in stillb...         1   
CME_ARR_U5MR: Annual rate of reduction in under...         1   
CME_MRM0: Neonatal mortality rate                          1   
CME_MRY0: Infant mortality rate                            1   
...                                                      ...   
WS_SCH_W-B: Proportion of schools with basic dr...         1   
WS_SCH_W-L: Proportion of schools with limited ...         1   
WS_SCH_W-N: Proportion of schools with no drink...         1   
WT_ADLS_15-19_ED_NEET: Percentage of adolescent...         1   
WT_ADLS_15-19_LAB_FRC_UNEMP: Percentage of adol...         1   

                                                    REF_AREA:Geographic area  \
INDICATOR:Indicator                                                            
CME_ARR_10T19: Annual Rate of Reduction in Mort...                       231   
CME_ARR_SBR: Annual rate of reduction in stillb...                       208   
CME_ARR_U5MR: Annual rate of reduction in under...                       231   
CME_MRM0: Neonatal mortality rate                                        239   
CME_MRY0: Infant mortality rate                                          239   
...                                                                      ...   
WS_SCH_W-B: Proportion of schools with basic dr...                       182   
WS_SCH_W-L: Proportion of schools with limited ...                       170   
WS_SCH_W-N: Proportion of schools with no drink...                       202   
WT_ADLS_15-19_ED_NEET: Percentage of adolescent...                       127   
WT_ADLS_15-19_LAB_FRC_UNEMP: Percentage of adol...                       188   

                                                    SEX:Sex  \
INDICATOR:Indicator                                           
CME_ARR_10T19: Annual Rate of Reduction in Mort...        1   
CME_ARR_SBR: Annual rate of reduction in stillb...        1   
CME_ARR_U5MR: Annual rate of reduction in under...        1   
CME_MRM0: Neonatal mortality rate                         1   
CME_MRY0: Infant mortality rate                           3   
...                                                     ...   
WS_SCH_W-B: Proportion of schools with basic dr...        1   
WS_SCH_W-L: Proportion of schools with limited ...        1   
WS_SCH_W-N: Proportion of schools with no drink...        1   
WT_ADLS_15-19_ED_NEET: Percentage of adolescent...        3   
WT_ADLS_15-19_LAB_FRC_UNEMP: Percentage of adol...        3   

                                                    TIME_PERIOD:Time period  \
INDICATOR:Indicator                                                           
CME_ARR_10T19: Annual Rate of Reduction in Mort...                        1   
CME_ARR_SBR: Annual rate of reduction in stillb...                        1   
CME_ARR_U5MR: Annual rate of reduction in under...                        1   
CME_MRM0: Neonatal mortality rate                                        70   
CME_MRY0: Infant mortality rate                                          87   
...                                                                     ...   
WS_SCH_W-B: Proportion of schools with basic dr...                       22   
WS_SCH_W-L: Proportion of schools with limited ...                       22   
WS_SCH_W-N: Proportion of schools with no drink...                       22   
WT_ADLS_15-19_ED_NEET: Percentage of adolescent...                       22   
WT_ADLS_15-19_LAB_FRC_UNEMP: Percentage of adol...                       12   

                                                    OBS_VALUE:Observation Value  \
INDICATOR:Indicator                                                               
CME_ARR_10T19: Annual Rate of Reduction in Mort...                           62   
CME_ARR_SBR: Annual rate of reduction in stillb...                          206  

In [26]:
CB_Ind[CB_Ind.index.str.contains("birt")]

DATAFLOW  \
INDICATOR:Indicator                                            
CME_ARR_SBR: Annual rate of reduction in stillb...         1   
CME_SB: Stillbirths                                        1   
CME_SBR: Stillbirth rate                                   1   
DM_BRTS: Number of births                                  1   
HVA_PED_EID_CVG: Per cent of infants born to pr...         1   
HVA_PED_EID_NUM: Reported number of infants bor...         1   
IM_BCG: Percentage of live births who received ...         1   
IM_HEPBB: Percentage of live births who receive...         1   
IM_PAB: Percentage of newborns protected at bir...         1   
MNCH_ABR: Adolescent birth rate (number of live...         1   
MNCH_BIRTH18: Early childbearing - percentage o...         1   
MNCH_LIFE_EXPECTANCY: Life expectancy at birth ...         1   
MNCH_MMR: Maternal mortality ratio (number of m...         1   
MNCH_PNCMOM: Postnatal care for mothers - perce...         1   
MNCH_SAB: Skilled birth attendant - percentage ...         1   
NT_BW_LBW: Prevalence of low birth weight among...         1   
NT_BW_LBW_MOD: Number (in thousands) of live bi...         1   
NT_BW_LBW_MOD_NUMTH: Number (in thousands) of l...         1   
NT_BW_UNW: Percentage of births without a birth...         1   
PT_CHLD_Y0T4_REG: Percentage of children under ...         1   

                                                    REF_AREA:Geographic area  \
INDICATOR:Indicator                                                            
CME_ARR_SBR: Annual rate of reduction in stillb...                       208   
CME_SB: Stillbirths                                                      239   
CME_SBR: Stillbirth rate                                                 239   
DM_BRTS: Number of births                                                252   
HVA_PED_EID_CVG: Per cent of infants born to pr...                        95   
HVA_PED_EID_NUM: Reported number of infants bor...                        95   
IM_BCG: Percentage of live births who received ...                       195   
IM_HEPBB: Percentage of live births who receive...                       133   
IM_PAB: Percentage of newborns protected at bir...                       122   
MNCH_ABR: Adolescent birth rate (number of live...                       232   
MNCH_BIRTH18: Early childbearing - percentage o...                       150   
MNCH_LIFE_EXPECTANCY: Life expectancy at birth ...                       245   
MNCH_MMR: Maternal mortality ratio (number of m...                       206   
MNCH_PNCMOM: Postnatal care for mothers - perce...                       141   
MNCH_SAB: Skilled birth attendant - percentage ...                       243   
NT_BW_LBW: Prevalence of low birth weight among...                       147   
NT_BW_LBW_MOD: Number (in thousands) of live bi...                       214   
NT_BW_LBW_MOD_NUMTH: Number (in thousands) of l...                       214   
NT_BW_UNW: Percentage of births without a birth...                       178   
PT_CHLD_Y0T4_REG: Percentage of children under ...                       189   

                                                    SEX:Sex  \
INDICATOR:Indicator                                           
CME_ARR_SBR: Annual rate of reduction in stillb...        1   
CME_SB: Stillbirths                                       1   
CME_SBR: Stillbirth rate                                  1   
DM_BRTS: Number of births                                 1   
HVA_PED_EID_CVG: Per cent of infants born to pr...        1   
HVA_PED_EID_NUM: Reported number of infants bor...        1   
IM_BCG: Percentage of live births who received ...        1   
IM_HEPBB: Percentage of live births who receive...        1   
IM_PAB: Percentage of newborns protected at bir...        1   
MNCH_ABR: Adolescent birth rate (number of live...        1   
MNCH_BIRTH18: Early childbearing - percentage o...        1   
MNCH_LIFE_EXPECTANCY: Life expectancy at birth ...        1   


In [27]:
CB_Ind[CB_Ind.index.str.contains("PT_CHLD_Y0T4_REG")]

DATAFLOW  \
INDICATOR:Indicator                                            
PT_CHLD_Y0T4_REG: Percentage of children under ...         1   

                                                    REF_AREA:Geographic area  \
INDICATOR:Indicator                                                            
PT_CHLD_Y0T4_REG: Percentage of children under ...                       189   

                                                    SEX:Sex  \
INDICATOR:Indicator                                           
PT_CHLD_Y0T4_REG: Percentage of children under ...        3   

                                                    TIME_PERIOD:Time period  \
INDICATOR:Indicator                                                           
PT_CHLD_Y0T4_REG: Percentage of children under ...                       15   

                                                    OBS_VALUE:Observation Value  \
INDICATOR:Indicator                                                               
PT_CHLD_Y0T4_REG: Percentage of children under ...                          237   

                                                    UNIT_MULTIPLIER:Unit multiplier  \
INDICATOR:Indicator                                                                   
PT_CHLD_Y0T4_REG: Percentage of children under ...                                0   

                                                    UNIT_MEASURE:Unit of measure  \
INDICATOR:Indicator                                                                
PT_CHLD_Y0T4_REG: Percentage of children under ...                             1   

                                                    OBS_STATUS:Observation Status  \
INDICATOR:Indicator                                                                 
PT_CHLD_Y0T4_REG: Percentage of children under ...                              3   

                                                    OBS_CONF:Observation confidentaility  \
INDICATOR:Indicator                                                                        
PT_CHLD_Y0T4_REG: Percentage of children under ...                                     1   

                                                    LOWER_BOUND:Lower Bound  \
INDICATOR:Indicator                                                           
PT_CHLD_Y0T4_REG: Percentage of children under ...                        0   

                                                    ...  \
INDICATOR:Indicator                                 ...   
PT_CHLD_Y0T4_REG: Percentage of children under ...  ...   

                                                    WGTD_SAMPL_SIZE:Weighted Sample Size  \
INDICATOR:Indicator                                                                        
PT_CHLD_Y0T4_REG: Percentage of children under ...                                     0   

                                                    OBS_FOOTNOTE:Observation footnote  \
INDICATOR:Indicator                                                                     
PT_CHLD_Y0T4_REG: Percentage of children under ...                                 51   

                                                    SERIES_FOOTNOTE:Series footnote  \
INDICATOR:Indicator                                                                   
PT_CHLD_Y0T4_REG: Percentage of children under ...                                0   

                                                    DATA_SOURCE:Data Source  \
INDICATOR:Indicator                                                           
PT_CHLD_Y0T4_REG: Percentage of children under ...                       79   

                                                    SOURCE_LINK:Citation of or link to the data source  \
INDICATOR:Indicator                                                                                      
PT_CHLD_Y0T4_REG: Percentage of children under ...                                                  0    

                                                    CUSTODIAN:Custodian  \
INDICATOR:Indicator                  

*PT_CHLD_Y0T4_REG: Percentage of children under age 5 whose births are registered* is the value within `INDICATOR:Indicator` column we are interested in. 
There are 189 geographic areas with information on childbirth percentage. Let's analyse `REF_AREA:Geographic area` column a bit more.

In [28]:
Geos = CB_percent.groupby('REF_AREA:Geographic area').nunique()
Geos

DATAFLOW  INDICATOR:Indicator  SEX:Sex  \
REF_AREA:Geographic area                                           
ABW: Aruba                       1                   42        3   
AFG: Afghanistan                 1                  293        3   
AGO: Angola                      1                  304        3   
AIA: Anguilla                    1                   57        3   
ALB: Albania                     1                  301        3   
...                            ...                  ...      ...   
XKX: Kosovo                      1                   47        3   
YEM: Yemen                       1                  314        3   
ZAF: South Africa                1                  314        3   
ZMB: Zambia                      1                  330        3   
ZWE: Zimbabwe                    1                  346        3   

                          TIME_PERIOD:Time period  \
REF_AREA:Geographic area                            
ABW: Aruba                                     73   
AFG: Afghanistan                               73   
AGO: Angola                                    73   
AIA: Anguilla                                  73   
ALB: Albania                                   73   
...                                           ...   
XKX: Kosovo                                    73   
YEM: Yemen                                     73   
ZAF: South Africa                              73   
ZMB: Zambia                                    73   
ZWE: Zimbabwe                                  73   

                          OBS_VALUE:Observation Value  \
REF_AREA:Geographic area                                
ABW: Aruba                                       2636   
AFG: Afghanistan                                 5419   
AGO: Angola                                      5223   
AIA: Anguilla                                    2441   
ALB: Albania                                     4907   
...                                               ...   
XKX: Kosovo                                      2471   
YEM: Yemen                                       5577   
ZAF: South Africa                                5602   
ZMB: Zambia                                      6196   
ZWE: Zimbabwe                                    6389   

                          UNIT_MULTIPLIER:Unit multiplier  \
REF_AREA:Geographic area                                    
ABW: Aruba                                              2   
AFG: Afghanistan                                        2   
AGO: Angola                                             2   
AIA: Anguilla                                           2   
ALB: Albania                                            2   
...                                                   ...   
XKX: Kosovo                                             2   
YEM: Yemen                                              2   
ZAF: South Africa                                       2   
ZMB: Zambia                                             2   
ZWE: Zimbabwe                                           2   

                          UNIT_MEASURE:Unit of measure  \
REF_AREA:Geographic area                                 
ABW: Aruba                                           8   
AFG: Afghanistan                                    25   
AGO: Angola                                         25   
AIA: Anguilla                                        7   
ALB: Albania                                        23   
...                                                ...   
XKX: Kosovo                                          6   
YEM: Yemen                                          25   
ZAF: South Africa                                   25   
ZMB: Zambia                                         25   
ZWE: Zimbabwe                                       25   

                          OBS_STATUS:Observation Status  \
REF_AREA:Geographic area                                  
ABW: Aruba                                

In [29]:
Geos[Geos.index.str.contains(":")].shape

(330, 21)

Geos areas contain three leter acronyms followed by a `:`. This naming convention may come in handy later on.

In [30]:
CB_percent[CB_percent['INDICATOR:Indicator']=="PT_CHLD_Y0T4_REG: Percentage of children under age 5 whose births are registered"].head

<bound method NDFrame.head of                                                   DATAFLOW  \
6499     UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indi...   
6500     UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indi...   
6501     UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indi...   
14765    UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indi...   
14766    UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indi...   
...                                                    ...   
1635966  UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indi...   
1635967  UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indi...   
1644676  UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indi...   
1644677  UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indi...   
1644678  UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indi...   

        REF_AREA:Geographic area  \
6499            AFG: Afghanistan   
6500            AFG: Afghanistan   
6501            AFG: Afghanistan   
14765               ALB: Albania   
14766               ALB: Albania   
...      

In [ ]:
CB_Ind.reset_index

In [ ]:
CB_Ind.index

In [ ]:
CB_Ind.columns

In [ ]:
CB_Ind.info

In [ ]:
CB_Ind.set_index("DATAFLOW")

In [ ]:
unique_indicator =  CB_Ind['index_column']

In [ ]:
unique_indicator

In [ ]:
df[df['ids'].str.contains("ball")]

In [ ]:
CB_percent_opt = CB_percent["REF_AREA:Geographic area","INDICATOR:Indicator","TIME_PERIOD:Time period","UNIT_MULTIPLIER:Unit multiplier",""]

In [ ]:
CB_percent.head(5)

#### Further analysis and filtering out non-needed column data

Currently, we are only interested in the % of childbirths registered, and can notice that for `AFG: Afganistan` there are values for Life expectancy in the data set. Also `DATAFLOW` column appear to offer not much value for us. Let's explore the values in those (and other) columns.

In [ ]:
CB_percent['DATAFLOW'].values

The value `UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indicators` seems to be repeating within the `DATAFLOW` column. Let's check if there are any other values contained.

In [ ]:
Examine = CB_percent[~CB_percent["DATAFLOW"].isin(["UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indicators"])]
Examine

No, the value `UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indicators` is the only one within the `DATAFLOW` column, hence we should drop it from the `Filtered_CB_percent` dataset we are planning to create later on.

In [ ]:
Examine = CB_percent[~CB_percent["SEX:Sex"].isin(["_T: Total"])]
Examine

The value `SEX:Sex` is the same as it contains only one value within (ie. `_T: Total`) we should drop it from the `Filtered_CB_percent` as well.

In [ ]:
Examine1 = CB_percent[~CB_percent["UNIT_MULTIPLIER:Unit multiplier"].isin(["0: Units"])]
Examine1

In [ ]:
Examine1 = Examine1[~Examine1["UNIT_MULTIPLIER:Unit multiplier"].isna()]
Examine1

Simiar is true for `UNIT_MULTIPLIER:Unit multiplier` with only one value of `0: Units` and 142 empty rows.

In [ ]:
Examine1 = CB_percent[~CB_percent["UNIT_MEASURE:Unit of measure"].isin(["YR: Years"])]
Examine1

In [ ]:
Examine2 = Examine1[~Examine1["UNIT_MEASURE:Unit of measure"].isin(["PCNT: %"])]
Examine2

For `UNIT_MEASURE:Unit of measure` need to check if for every value of `PCNT: %` each of the values in column `INDICATOR:Indicator` is equal to `PT_CHLD_Y0T4_REG: Percentage of children under age 5 whose births are registered`

In [ ]:
Examine1 = CB_percent[~CB_percent["UNIT_MEASURE:Unit of measure"].isin(["YR: Years"])]
Examine2 = Examine1 [~Examine1 ["INDICATOR:Indicator"].isin(["PT_CHLD_Y0T4_REG: Percentage of children under age 5 whose births are registered"])]
Examine2

As per above check since for each row where `UNIT_MEASURE:Unit of measure` is equal to `PCNT: %` at the same time values in column `INDICATOR:Indicator` are all equal to `PT_CHLD_Y0T4_REG: Percentage of children under age 5 whose births are registered` then column `UNIT_MEASURE:Unit of measure` can also be discarded.

In [ ]:
CB_percent["OBS_STATUS:Observation Status"].value_counts()

In [ ]:
Examine = CB_percent[~CB_percent["OBS_STATUS:Observation Status"].isna()]
Examine

In [ ]:
Examine2 = CB_percent[CB_percent["OBS_STATUS:Observation Status"].isna()]
Examine2["OBS_STATUS:Observation Status"].value_counts()

In [ ]:
Estimated_CB_percent = CB_percent[CB_percent["OBS_STATUS:Observation Status"].isin(["E: Estimated value"])]
Estimated_CB_percent

In [ ]:
Reported_CB_percent = CB_percent[CB_percent["OBS_STATUS:Observation Status"].isin(["RP: Reported"])]
Reported_CB_percent

In [ ]:
Rd_CB_percent_sorted = Reported_CB_percent.sort_values(["OBS_VALUE:Observation Value"])
Rd_CB_percent_sorted

#### 2.1.1.3 Filtering out important data columns

In [ ]:
Filtered_Reported_CB_percent = Rd_CB_percent_sorted[["REF_AREA:Geographic area","TIME_PERIOD:Time period","OBS_VALUE:Observation Value"]]
Filtered_Reported_CB_percent

In [ ]:
Filtered_Reported_CB_percent_lessthan50 = Filtered_Reported_CB_percent[Filtered_Reported_CB_percent["OBS_VALUE:Observation Value"]<50]
Filtered_Reported_CB_percent_lessthan50

In [ ]:
Filtered_Reported_CB_percent_morethan80 = Filtered_Reported_CB_percent[Filtered_Reported_CB_percent["OBS_VALUE:Observation Value"]>80]
Filtered_Reported_CB_percent_morethan80

From `Filtered_Reported_CB_percent_morethan80` we can read out that 75 countries have reported child births percentage in over `80%` cases

### Observation: 75 countries have reported child births percentage in over `80%` cases

---

---

## Age of mothers at childbirth

In [ ]:
## Importing a data file into a panda dataframe

In [ ]:
Age_mothers_raw = pd.read_csv('SF_2_3_Age_mothers_childbirth.csv')

### Let's explore this data set

Investigating a dataframe and cleaning data

In [ ]:
Age_mothers_raw.info()

From info() I've learned that there are 51 rows and 94 columns of data 

In [ ]:
Age_mothers_raw.head(5)

Observations:
1. could first row be used for column index and first column as row index
2. looking at the first few rows I determined that there are some null values and the question was is if some of the rows/columns could be discarded

#### Setting first row as column index and first column as row index

In [ ]:
Age_mothers = Age_mothers_raw[:]
Age_mothers.columns=Age_mothers.iloc[0]
Age_mothers.head(3)

In [ ]:
Age_mothers_index = Age_mothers.set_index('Country')
Age_mothers_index.head(3)

In [ ]:
#Age_mothers.set_index('Country',inplace=True)

In [ ]:
Age_mothers_index.index.duplicated()

#### Checking for columns with Null values that can be discarded

In [ ]:
Age_mothers_index.isnull().sum()

In [ ]:
Age_mothers_index.dropna(axis=1,how='all').shape

In [ ]:
Age_mothers_index.dropna(axis=1,how='all',inplace=True)
Age_mothers_index

In [ ]:
Age_mothers_index.info()

In [ ]:
Age_mothers_index.dtypes[42]

---

---

# Visualisation